apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: job-hunt
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:GD6aUobMNNFR6xl1WpxMt27tZLHdOHIJrUbqsOn6iFcSXQUdhKIuc1+NT+qfm7SqtK04TsjDc/ZiggLYkAwBj2OrGw4qWkfCR42mj/QkOGRcLjbdwQ/33nIsTESUMKe07XOihaooeMIHDZIZ6jO7wvdc5jVtIxsJdnIW3oO4JBhCGDa8eIlwoA==,iv:ZBmnWS2rJboqZL0FjN1LNMqAXDQ9wj/w2ed+L8iG7iw=,tag:ZMGOVcMShBogJt1h+bp/FQ==,type:str]
sops:
    age:
        - recipient: age1ed4a57k6jfruc8lhez7k32lgfca5zdpc6hv5d6kk2n3kefxsy5kqn5auuh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHZoVDZ3anhQN0xCUlJY
            VHhUYjh1Rkcra3BTdnc4RHhtSlNCbjQvT0ZBCmplZWZ2VzNaMVVYa0p6ZGZTVCtC
            Q3RvRTk5WmtJRlpPTGljUWhLeE1TSGMKLS0tIDhFU0ljbE9WMkZTUmdoYjhWM2hR
            VnZzL0s0SzUzVU1KNkd1clNWWTM0SncK4NV2G+kem8YeoX1GnEFVxWrcEux5DC2N
            ioAJEKMLhGoDehZEk+DXWUpNBxzmOgaLZ2Vy919UtHfqN/QwOSnsyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T13:07:04Z"
    mac: ENC[AES256_GCM,data:8wwS55PZtM31Lsi2nx4QzM+U26p4fkEiOmxmYxKXCkZulo19Jrk/mGy9xnPCFmHCkkCwJExcxV8mniqh5haJWQA6OTLKGbatzFLJr3OzfF/difrMXqLwBf9mzeLW6YzwJlo2Dfjf8Hjl05eSDnyYhr+1npQp2ju2TeUTCCCS2vA=,iv:N2YotzthvoxMypEG54qLrmmqP25a56aP2VmFfIAWwHc=,tag:QaKIFv60ZpNZqyIBw7zkvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
