apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Y+8QgVQdFy242I4+rx4foSEj9yxwfwuMsBzIfdE8UygO80zYFw+2phdAB45sFxOyQgYpDvRkjdx3CxhbYNVye3pXq4KTLFynX0lmV2m6sviaLazGqXt4c1JWbAtZYraRTqR9SfculvzyfcM5nTl1bpo/ilH+4hqD6wQq2xrGQUnJpbFfFZP5TW6fiaF1uxdpKjg6tCVzwGGbQa54Lu2d2SGZvcY6jhQt/i1hb6W2YkJrVzyJY+uX4trT1hD3kPH8CDrbkR3seJhnKhhIVcZHOAsQMQqGHfevCJnmA95PJlitu4MvLcA5C2PtLAx30ow8,iv:sylL78nW8V6ZsU2JE1U3ldwFCuN6VjZE+ox0SKNUF8s=,tag:Ad1G1xBXUC1I8tdEdljdxA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: job-hunt
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1ed4a57k6jfruc8lhez7k32lgfca5zdpc6hv5d6kk2n3kefxsy5kqn5auuh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TUE4ZmxZL21VcThaR2Jw
            RE1xOEwzUXBoYk4xbi9Tb1pTMkRJdk1iTkdFCnpNZWxIbWFJMVBrQzRHaXdrMUVG
            VnRFTWVBakg1V3hTNy9OY3M2b29BMDQKLS0tIFFSUS9ybENLZlJvTEwrYnpBNFFP
            L3IwSllkbEVHaWVqb25IRFJEZjdaZTgK0sv1m1Ypfe2wwVCApnu1QFFcnxAvj7H8
            ntEz/lAStg7zngtqMjAmt9NFQ4+JAzlie2nms6epiT4zNOR6VxmEnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T14:21:09Z"
    mac: ENC[AES256_GCM,data:sw+YwHa4Nbk9SJ3HOtcVvNQjksSEP9gFHxbEilVDz9wNJz5IEGCJUASj4bn97eH4ejwryKP5PqJroHLTWM/68BoAmDn+mjDoj+vbWK33KiR0rQ3zuXjD5AVSBGjBu2iF5JRxeYMkBd317EWYTtnYj+bhmFmZ44ujAf5S7gHzjgw=,iv:4yvh1VLL4xRj2DuKl5srSsPqarvfuP93LJyyq76uMX4=,tag:qG4BGeeRW96SN1nRXdvFVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
