apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ghcr-pull-secret.enc.yaml
namespace: job-hunt
images:
  - name: ghcr.io/thadamski/job-discovery
    newTag: v0.1.3 # {"$imagepolicy": "flux-system:job-discovery:tag"}
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{name: ghcr-pull}]
    target:
      kind: Deployment
      name: job-discovery
