apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: job-hunt
images:
  - name: ghcr.io/thadamski/job-discovery
    newTag: latest # {"$imagepolicy": "flux-system:job-discovery:tag"}
