// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BoardKind.
const (
	Ashby      BoardKind = "ashby"
	Greenhouse BoardKind = "greenhouse"
	Lever      BoardKind = "lever"
)

// Valid indicates whether the value is a known member of the BoardKind enum.
func (e BoardKind) Valid() bool {
	switch e {
	case Ashby:
		return true
	case Greenhouse:
		return true
	case Lever:
		return true
	default:
		return false
	}
}

// Defines values for ListingStatus.
const (
	Applied     ListingStatus = "applied"
	Closed      ListingStatus = "closed"
	FilteredOut ListingStatus = "filtered_out"
	New         ListingStatus = "new"
	Passed      ListingStatus = "passed"
	Scored      ListingStatus = "scored"
	Shortlisted ListingStatus = "shortlisted"
)

// Valid indicates whether the value is a known member of the ListingStatus enum.
func (e ListingStatus) Valid() bool {
	switch e {
	case Applied:
		return true
	case Closed:
		return true
	case FilteredOut:
		return true
	case New:
		return true
	case Passed:
		return true
	case Scored:
		return true
	case Shortlisted:
		return true
	default:
		return false
	}
}

// Defines values for SkippedCompanyReason.
const (
	BoardUnsupported SkippedCompanyReason = "board_unsupported"
	Inactive         SkippedCompanyReason = "inactive"
	Unverified       SkippedCompanyReason = "unverified"
)

// Valid indicates whether the value is a known member of the SkippedCompanyReason enum.
func (e SkippedCompanyReason) Valid() bool {
	switch e {
	case BoardUnsupported:
		return true
	case Inactive:
		return true
	case Unverified:
		return true
	default:
		return false
	}
}

// BoardKind External job-board provider.
type BoardKind string

// Company defines model for Company.
type Company struct {
	Active bool `json:"active"`

	// BoardKind External job-board provider.
	BoardKind BoardKind `json:"board_kind"`

	// BoardSlug The company's identifier on the chosen board (e.g. `stripe` for `boards.greenhouse.io/stripe`).
	BoardSlug string     `json:"board_slug"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *uuid.UUID `json:"id,omitempty"`
	Name      string     `json:"name"`
	Notes     *string    `json:"notes,omitempty"`
	Priority  int        `json:"priority"`
	Tags      []string   `json:"tags"`
}

// CompanyCreate defines model for CompanyCreate.
type CompanyCreate struct {
	Active *bool `json:"active,omitempty"`

	// BoardKind External job-board provider.
	BoardKind BoardKind `json:"board_kind"`
	BoardSlug string    `json:"board_slug"`
	Name      string    `json:"name"`
	Notes     *string   `json:"notes,omitempty"`
	Priority  *int      `json:"priority,omitempty"`
	Tags      *[]string `json:"tags,omitempty"`
}

// CompanyRefreshOutcome defines model for CompanyRefreshOutcome.
type CompanyRefreshOutcome struct {
	// BoardKind External job-board provider.
	BoardKind BoardKind `json:"board_kind"`
	BoardSlug string    `json:"board_slug"`
	CompanyId uuid.UUID `json:"company_id"`

	// Error Set when this company failed; other counts will be 0.
	Error        *string `json:"error,omitempty"`
	ListingsNew  int     `json:"listings_new"`
	ListingsSeen int     `json:"listings_seen"`
	Name         string  `json:"name"`
}

// Listing defines model for Listing.
type Listing struct {
	CompanyId   uuid.UUID `json:"company_id"`
	Description string    `json:"description"`

	// ExternalId The board's native ID; unique per `(company_id, external_id)`.
	ExternalId string     `json:"external_id"`
	FetchedAt  *time.Time `json:"fetched_at,omitempty"`
	Id         *uuid.UUID `json:"id,omitempty"`
	Location   *string    `json:"location,omitempty"`
	PostedAt   *time.Time `json:"posted_at,omitempty"`

	// RawPayload Full board response, retained for re-extraction.
	RawPayload *map[string]interface{} `json:"raw_payload,omitempty"`
	Status     ListingStatus           `json:"status"`
	Title      string                  `json:"title"`
	Url        string                  `json:"url"`
}

// ListingStatus defines model for ListingStatus.
type ListingStatus string

// ListingUpdate Patch document. At least one field must be present.
type ListingUpdate struct {
	Status *ListingStatus `json:"status,omitempty"`
}

// Problem RFC 7807 problem details.
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`

	// RequestId Echo of the `X-Request-ID` header for correlation.
	RequestId *string `json:"request_id,omitempty"`
	Status    int     `json:"status"`

	// Title Short, human-readable summary.
	Title string `json:"title"`

	// Type A URI reference identifying the problem type.
	Type string `json:"type"`
}

// RefreshRequest Empty body means "all active+verified companies".
type RefreshRequest struct {
	// BoardKind External job-board provider.
	BoardKind *BoardKind `json:"board_kind,omitempty"`

	// CompanyId If set, only refresh this company.
	CompanyId *uuid.UUID `json:"company_id,omitempty"`
}

// RefreshResult defines model for RefreshResult.
type RefreshResult struct {
	Companies  []CompanyRefreshOutcome `json:"companies"`
	FinishedAt time.Time               `json:"finished_at"`
	Skipped    []SkippedCompany        `json:"skipped"`
	StartedAt  time.Time               `json:"started_at"`
	Totals     struct {
		CompaniesFetched int `json:"companies_fetched"`
		Errors           int `json:"errors"`
		ListingsNew      int `json:"listings_new"`
		ListingsSeen     int `json:"listings_seen"`
	} `json:"totals"`
}

// SkippedCompany defines model for SkippedCompany.
type SkippedCompany struct {
	CompanyId uuid.UUID            `json:"company_id"`
	Name      string               `json:"name"`
	Reason    SkippedCompanyReason `json:"reason"`
}

// SkippedCompanyReason defines model for SkippedCompany.Reason.
type SkippedCompanyReason string

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// Conflict RFC 7807 problem details.
type Conflict = Problem

// InternalError RFC 7807 problem details.
type InternalError = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// UnprocessableEntity RFC 7807 problem details.
type UnprocessableEntity = Problem

// ListCompaniesParams defines parameters for ListCompanies.
type ListCompaniesParams struct {
	// Active Filter by `active` flag. Omit to return all.
	Active    *bool      `form:"active,omitempty" json:"active,omitempty"`
	BoardKind *BoardKind `form:"board_kind,omitempty" json:"board_kind,omitempty"`
}

// ListListingsParams defines parameters for ListListings.
type ListListingsParams struct {
	Status *ListingStatus `form:"status,omitempty" json:"status,omitempty"`

	// Company Filter by company UUID or `board_slug`.
	Company *string `form:"company,omitempty" json:"company,omitempty"`

	// MinScore Only return listings whose latest score (from `job-scoring`) is at
	// least this value. Requires an inter-service call; omit for the
	// fast path. Range 0.0-10.0.
	MinScore *float32 `form:"min_score,omitempty" json:"min_score,omitempty"`
	Limit    *int     `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *int     `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateCompanyJSONRequestBody defines body for CreateCompany for application/json ContentType.
type CreateCompanyJSONRequestBody = CompanyCreate

// UpdateListingJSONRequestBody defines body for UpdateListing for application/json ContentType.
type UpdateListingJSONRequestBody = ListingUpdate

// TriggerRefreshJSONRequestBody defines body for TriggerRefresh for application/json ContentType.
type TriggerRefreshJSONRequestBody = RefreshRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List target companies.
	// (GET /api/v1/job-discovery/companies)
	ListCompanies(w http.ResponseWriter, r *http.Request, params ListCompaniesParams)
	// Register a new target company.
	// (POST /api/v1/job-discovery/companies)
	CreateCompany(w http.ResponseWriter, r *http.Request)
	// List discovered listings.
	// (GET /api/v1/job-discovery/listings)
	ListListings(w http.ResponseWriter, r *http.Request, params ListListingsParams)
	// Fetch a single listing.
	// (GET /api/v1/job-discovery/listings/{id})
	GetListing(w http.ResponseWriter, r *http.Request, id uuid.UUID)
	// Update mutable listing fields (currently `status` only).
	// (PATCH /api/v1/job-discovery/listings/{id})
	UpdateListing(w http.ResponseWriter, r *http.Request, id uuid.UUID)
	// Trigger a fetch against external job boards.
	// (POST /api/v1/job-discovery/refresh)
	TriggerRefresh(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List target companies.
// (GET /api/v1/job-discovery/companies)
func (_ Unimplemented) ListCompanies(w http.ResponseWriter, r *http.Request, params ListCompaniesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new target company.
// (POST /api/v1/job-discovery/companies)
func (_ Unimplemented) CreateCompany(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List discovered listings.
// (GET /api/v1/job-discovery/listings)
func (_ Unimplemented) ListListings(w http.ResponseWriter, r *http.Request, params ListListingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a single listing.
// (GET /api/v1/job-discovery/listings/{id})
func (_ Unimplemented) GetListing(w http.ResponseWriter, r *http.Request, id uuid.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update mutable listing fields (currently `status` only).
// (PATCH /api/v1/job-discovery/listings/{id})
func (_ Unimplemented) UpdateListing(w http.ResponseWriter, r *http.Request, id uuid.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger a fetch against external job boards.
// (POST /api/v1/job-discovery/refresh)
func (_ Unimplemented) TriggerRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCompanies operation middleware
func (siw *ServerInterfaceWrapper) ListCompanies(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCompaniesParams

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "active", r.URL.Query(), &params.Active, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "active"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "active", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "board_kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "board_kind", r.URL.Query(), &params.BoardKind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "board_kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "board_kind", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCompanies(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCompany operation middleware
func (siw *ServerInterfaceWrapper) CreateCompany(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCompany(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListListings operation middleware
func (siw *ServerInterfaceWrapper) ListListings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListListingsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "company" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "company", r.URL.Query(), &params.Company, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "company"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "company", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "min_score" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_score", r.URL.Query(), &params.MinScore, runtime.BindQueryParameterOptions{Type: "number", Format: "float"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "min_score"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_score", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListListings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetListing operation middleware
func (siw *ServerInterfaceWrapper) GetListing(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetListing(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateListing operation middleware
func (siw *ServerInterfaceWrapper) UpdateListing(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateListing(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerRefresh operation middleware
func (siw *ServerInterfaceWrapper) TriggerRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/job-discovery/companies", wrapper.ListCompanies)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/job-discovery/companies", wrapper.CreateCompany)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/job-discovery/listings", wrapper.ListListings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/job-discovery/listings/{id}", wrapper.GetListing)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/job-discovery/listings/{id}", wrapper.UpdateListing)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/job-discovery/refresh", wrapper.TriggerRefresh)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type InternalErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

type ListCompaniesRequestObject struct {
	Params ListCompaniesParams
}

type ListCompaniesResponseObject interface {
	VisitListCompaniesResponse(w http.ResponseWriter) error
}

type ListCompanies200JSONResponse []Company

func (response ListCompanies200JSONResponse) VisitListCompaniesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCompanies500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListCompanies500ApplicationProblemPlusJSONResponse) VisitListCompaniesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCompanyRequestObject struct {
	Body *CreateCompanyJSONRequestBody
}

type CreateCompanyResponseObject interface {
	VisitCreateCompanyResponse(w http.ResponseWriter) error
}

type CreateCompany201ResponseHeaders struct {
	Location *string
}

type CreateCompany201JSONResponse struct {
	Body    Company
	Headers CreateCompany201ResponseHeaders
}

func (response CreateCompany201JSONResponse) VisitCreateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCompany400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateCompany400ApplicationProblemPlusJSONResponse) VisitCreateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCompany409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response CreateCompany409ApplicationProblemPlusJSONResponse) VisitCreateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCompany500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response CreateCompany500ApplicationProblemPlusJSONResponse) VisitCreateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListListingsRequestObject struct {
	Params ListListingsParams
}

type ListListingsResponseObject interface {
	VisitListListingsResponse(w http.ResponseWriter) error
}

type ListListings200JSONResponse []Listing

func (response ListListings200JSONResponse) VisitListListingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListListings400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListListings400ApplicationProblemPlusJSONResponse) VisitListListingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListListings500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListListings500ApplicationProblemPlusJSONResponse) VisitListListingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetListingRequestObject struct {
	Id uuid.UUID `json:"id"`
}

type GetListingResponseObject interface {
	VisitGetListingResponse(w http.ResponseWriter) error
}

type GetListing200JSONResponse Listing

func (response GetListing200JSONResponse) VisitGetListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetListing404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetListing404ApplicationProblemPlusJSONResponse) VisitGetListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetListing500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetListing500ApplicationProblemPlusJSONResponse) VisitGetListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateListingRequestObject struct {
	Id   uuid.UUID `json:"id"`
	Body *UpdateListingJSONRequestBody
}

type UpdateListingResponseObject interface {
	VisitUpdateListingResponse(w http.ResponseWriter) error
}

type UpdateListing200JSONResponse Listing

func (response UpdateListing200JSONResponse) VisitUpdateListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateListing400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response UpdateListing400ApplicationProblemPlusJSONResponse) VisitUpdateListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateListing404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UpdateListing404ApplicationProblemPlusJSONResponse) VisitUpdateListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateListing422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response UpdateListing422ApplicationProblemPlusJSONResponse) VisitUpdateListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateListing500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response UpdateListing500ApplicationProblemPlusJSONResponse) VisitUpdateListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerRefreshRequestObject struct {
	Body *TriggerRefreshJSONRequestBody
}

type TriggerRefreshResponseObject interface {
	VisitTriggerRefreshResponse(w http.ResponseWriter) error
}

type TriggerRefresh200JSONResponse RefreshResult

func (response TriggerRefresh200JSONResponse) VisitTriggerRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerRefresh400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response TriggerRefresh400ApplicationProblemPlusJSONResponse) VisitTriggerRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerRefresh404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response TriggerRefresh404ApplicationProblemPlusJSONResponse) VisitTriggerRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerRefresh500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response TriggerRefresh500ApplicationProblemPlusJSONResponse) VisitTriggerRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List target companies.
	// (GET /api/v1/job-discovery/companies)
	ListCompanies(ctx context.Context, request ListCompaniesRequestObject) (ListCompaniesResponseObject, error)
	// Register a new target company.
	// (POST /api/v1/job-discovery/companies)
	CreateCompany(ctx context.Context, request CreateCompanyRequestObject) (CreateCompanyResponseObject, error)
	// List discovered listings.
	// (GET /api/v1/job-discovery/listings)
	ListListings(ctx context.Context, request ListListingsRequestObject) (ListListingsResponseObject, error)
	// Fetch a single listing.
	// (GET /api/v1/job-discovery/listings/{id})
	GetListing(ctx context.Context, request GetListingRequestObject) (GetListingResponseObject, error)
	// Update mutable listing fields (currently `status` only).
	// (PATCH /api/v1/job-discovery/listings/{id})
	UpdateListing(ctx context.Context, request UpdateListingRequestObject) (UpdateListingResponseObject, error)
	// Trigger a fetch against external job boards.
	// (POST /api/v1/job-discovery/refresh)
	TriggerRefresh(ctx context.Context, request TriggerRefreshRequestObject) (TriggerRefreshResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCompanies operation middleware
func (sh *strictHandler) ListCompanies(w http.ResponseWriter, r *http.Request, params ListCompaniesParams) {
	var request ListCompaniesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCompanies(ctx, request.(ListCompaniesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCompanies")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCompaniesResponseObject); ok {
		if err := validResponse.VisitListCompaniesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCompany operation middleware
func (sh *strictHandler) CreateCompany(w http.ResponseWriter, r *http.Request) {
	var request CreateCompanyRequestObject

	var body CreateCompanyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCompany(ctx, request.(CreateCompanyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCompany")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCompanyResponseObject); ok {
		if err := validResponse.VisitCreateCompanyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListListings operation middleware
func (sh *strictHandler) ListListings(w http.ResponseWriter, r *http.Request, params ListListingsParams) {
	var request ListListingsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListListings(ctx, request.(ListListingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListListings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListListingsResponseObject); ok {
		if err := validResponse.VisitListListingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetListing operation middleware
func (sh *strictHandler) GetListing(w http.ResponseWriter, r *http.Request, id uuid.UUID) {
	var request GetListingRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetListing(ctx, request.(GetListingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetListing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetListingResponseObject); ok {
		if err := validResponse.VisitGetListingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateListing operation middleware
func (sh *strictHandler) UpdateListing(w http.ResponseWriter, r *http.Request, id uuid.UUID) {
	var request UpdateListingRequestObject

	request.Id = id

	var body UpdateListingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateListing(ctx, request.(UpdateListingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateListing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateListingResponseObject); ok {
		if err := validResponse.VisitUpdateListingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerRefresh operation middleware
func (sh *strictHandler) TriggerRefresh(w http.ResponseWriter, r *http.Request) {
	var request TriggerRefreshRequestObject

	var body TriggerRefreshJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerRefresh(ctx, request.(TriggerRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerRefresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerRefreshResponseObject); ok {
		if err := validResponse.VisitTriggerRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
