apiVersion: v1
kind: Service
metadata:
  name: job-discovery
  namespace: job-hunt
  labels:
    app: job-discovery
spec:
  type: ClusterIP
  selector:
    app: job-discovery
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
