// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, board_kind, board_slug, priority, tags, notes, active, created_at
FROM companies
WHERE ($1::boolean  IS NULL OR active     = $1::boolean)
  AND ($2::text IS NULL OR board_kind = $2::text)
ORDER BY priority ASC, name ASC`

type ListCompaniesParams struct {
	Active    *bool   `json:"active"`
	BoardKind *string `json:"board_kind"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.Active, arg.BoardKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoardKind,
			&i.BoardSlug,
			&i.Priority,
			&i.Tags,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, board_kind, board_slug, priority, tags, notes, active, created_at
FROM companies
WHERE id = $1`

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BoardKind,
		&i.BoardSlug,
		&i.Priority,
		&i.Tags,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
    name, board_kind, board_slug, priority, tags, notes, active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, board_kind, board_slug, priority, tags, notes, active, created_at`

type CreateCompanyParams struct {
	Name      string   `json:"name"`
	BoardKind string   `json:"board_kind"`
	BoardSlug string   `json:"board_slug"`
	Priority  int16    `json:"priority"`
	Tags      []string `json:"tags"`
	Notes     *string  `json:"notes"`
	Active    bool     `json:"active"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(
		ctx, createCompany,
		arg.Name,
		arg.BoardKind,
		arg.BoardSlug,
		arg.Priority,
		arg.Tags,
		arg.Notes,
		arg.Active,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BoardKind,
		&i.BoardSlug,
		&i.Priority,
		&i.Tags,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveCompanies = `-- name: GetActiveCompanies :many
SELECT id, name, board_kind, board_slug, priority, tags, notes, active, created_at
FROM companies
WHERE active = TRUE
  AND ($1::text IS NULL OR board_kind = $1::text)
ORDER BY priority ASC, name ASC`

func (q *Queries) GetActiveCompanies(ctx context.Context, boardKind *string) ([]Company, error) {
	rows, err := q.db.Query(ctx, getActiveCompanies, boardKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoardKind,
			&i.BoardSlug,
			&i.Priority,
			&i.Tags,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
