// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Company struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	BoardKind string    `json:"board_kind"`
	BoardSlug string    `json:"board_slug"`
	Priority  int16     `json:"priority"`
	Tags      []string  `json:"tags"`
	Notes     *string   `json:"notes"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
}

type Listing struct {
	ID          uuid.UUID  `json:"id"`
	CompanyID   uuid.UUID  `json:"company_id"`
	ExternalID  string     `json:"external_id"`
	Title       string     `json:"title"`
	Location    *string    `json:"location"`
	URL         string     `json:"url"`
	Description string     `json:"description"`
	RawPayload  []byte     `json:"raw_payload"`
	PostedAt    *time.Time `json:"posted_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	Status      string     `json:"status"`
}
